---
title: Datenschutz
---

Eine Nutzung der Internetseite von "Masterarbeit - "Assassin's Creed" als Spiegel der Realität?" ist grundsätzlich ohne jede Angabe personenbezogener Daten möglich. Sollte die Verarbeitung personenbezogener Daten erforderlich sein und besteht für eine solche Verarbeitung keine gesetzliche Grundlage, wird eine Einwilligung der betroffenen Person eingeholt.

Die Verarbeitung personenbezogener Daten, beispielsweise des Namens, der Anschrift, E-Mail-Adresse oder Telefonnummer einer betroffenen Person, erfolgt stets im Einklang mit der Datenschutz-Grundverordnung und in Übereinstimmung mit den für "Masterarbeit - "Assassin's Creed" als Spiegel der Realität?" geltenden landesspezifischen Datenschutzbestimmungen. Mittels dieser Datenschutzerklärung möchte "Masterarbeit - "Assassin's Creed" als Spiegel der Realität?" die Öffentlichkeit über Art, Umfang und Zweck der erhobenen, genutzten und verarbeiteten personenbezogenen Daten informieren. Ferner werden betroffene Personen mittels dieser Datenschutzerklärung über die ihnen zustehenden Rechte aufgeklärt.
Für Angaben von personenbezogene Daten in externen Links ist "Masterarbeit - "Assassin's Creed" als Spiegel der Realität?" nicht zuständig und haftbar. 

#### Name und Kontakt der Verantwortlichen der Website

Ann-Kathrin Susanne Weber \
Mail: weannkat@students.uni-mainz.de \
GitHub: https://github.com/Weannkat/Masterarbeit-Assassin-s-Creed-Monteriggioni \