---
title: Quellen
---

*Es werden lediglich die Quellen aufgelistet, die im Rahmen dieser Website verwendet wurden. Für eine Liste der in der Masterarbeit verwendeten Quellen wird an dieser Stelle auf das Quellenverzeichnis der Masterarbeit verwiesen.*

## Bildquellen

- Assassin's Creed Wiki. Renovierte Villa Auditore. https://assassinscreed.fandom.com/pt-br/wiki/Villa_Auditore (Letzter Zugriff am 07.09.2026).
- Assassin's Creed Wiki. Villa Auditore (heruntergekommen) https://assassinscreed.fandom.com/de/wiki/Villa_Auditore (Letzter Zugriff am 07.09.2026).
- Betti, Luca. Monteriggioni Luftaufnahme. In: https://www.visittuscany.com/de/staedte-und-ortschaften/monteriggioni-mittelalter-toskana/ (Letzter Zugriff am 07.09.2026).
- Creative Commons. Downloads. https://creativecommons.org/mission/downloads/ (Letzter Zugriff am 07.09.2026).
- Hochschule Mainz. Nutzungsbedingungen des Logos der Hochschule Mainz. https://www.hs-mainz.de/pressemedien/logo/(Letzter Zugriff am 07.09.2026).
- Johannes Gutenberg-Universität. JGU Corporate Design: Universitäts-Logos.https://www.zdv.uni-mainz.de/jgu-corporate-design-universitaets-logos/ (Letzter Zugriff am 07.09.2026).
- QGIS. Visual Style Guide. Version 1.0. https://qgis.org/styleguide/ (Letzter Zugriff am 11.09.2026).
- Sailko. Villa di maiano. https://commons.wikimedia.org/wiki/File:Villa_di_maiano_01.JPG (Letzter Zugriff am 07.09.2026).
- Ubisoft. Assassin's Creed: Brotherhood. Entwickelt von Ubisoft Montreal, Ubisoft, 2010.
- (Ubisoft). Granjon, Mathieu. Assassin's Creed 2 - Villa Auditore & Monteriggioni - Art Director | Ubisoft Annecy. In: Artstation.com. https://mat_granjon.artstation.com/projects/N5Bw1b (Letzter Zugriff am 08.09.2026).
- Unbekannt. Villa di Maiano for wedding receptions in Florence. In: Exclusive Italy Weddings. https://www.exclusiveitalyweddings.com/florence-wedding-at-villa-di-maiano (Letzter Zugriff am 04.09.2026).
- Unbekannter Nutzer. Notre-Dame structure in real life and Assassin's Creed Unity game comparison. In: Reddit.com. www.reddit.com/r/gaming/comments/uu4z9g/notredame_structure_in_real_life_and_assassins/#lightbox (Letzter Zugriff am 22.09.2026). 


## Textquellen
- Unbekannter Autor. A Room with a View: a glimpse on E. M. Forster and James Ivory’s Florence. In: Florence-tickets.com.
https://www.florence-tickets.com/blog/florence/a-room-with-a-view-a-glimpse-on-e-m-forster-and-james-
ivorys-florence (Letzter Zugriff am 22.07.2026).
- Unbekannter Autor. Fattoria di Maiano. In: Grandi Giardini Italiani. https://www.grandigiardini.it/lang_EN/297-visit-Fattoria-
di-Maiano-event-tickets#part3 (Letzter Zugriff am 28.07.2026)
- Lee, Sidney. Leader, John Temple. In: Dictionary of National Biography, 1912 supplement, Volume 2. https://en.wikisource.org/wiki/Dictionary_of_National_Biography,_1912_supplement/Leader,_John_Temple (Letzter Zugriff am 07.09.2026).